resources:
- name: rootfs-repo
  type: git
  source:
    branch: master
    uri: {{rootfs_repo}}
jobs:
- name: build
  serial: true
  plan:
  - get: rootfs-repo
  - task: build
    image: rootfs-repo
    config:
      platform: linux
      run:
        path: sh
        args:
        - '-c'
        - |
          ping -c1 8.8.8.8
